// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Burgerking struct {
	ID           int32       `json:"id"`
	Name         string      `json:"name"`
	ImageUrl     pgtype.Text `json:"imageUrl"`
	Calories     pgtype.Text `json:"calories"`
	CaloriesUnit pgtype.Text `json:"caloriesUnit"`
	Protein      pgtype.Text `json:"protein"`
	ProteinUnit  pgtype.Text `json:"proteinUnit"`
	Carbs        pgtype.Text `json:"carbs"`
	CarbsUnit    pgtype.Text `json:"carbsUnit"`
	Fat          pgtype.Text `json:"fat"`
	FatUnit      pgtype.Text `json:"fatUnit"`
	Category     pgtype.Text `json:"category"`
}

type Chickfila struct {
	ID           int32       `json:"id"`
	Name         string      `json:"name"`
	ImageUrl     pgtype.Text `json:"imageUrl"`
	Calories     pgtype.Text `json:"calories"`
	CaloriesUnit pgtype.Text `json:"caloriesUnit"`
	Protein      pgtype.Text `json:"protein"`
	ProteinUnit  pgtype.Text `json:"proteinUnit"`
	Carbs        pgtype.Text `json:"carbs"`
	CarbsUnit    pgtype.Text `json:"carbsUnit"`
	Fat          pgtype.Text `json:"fat"`
	FatUnit      pgtype.Text `json:"fatUnit"`
	Category     pgtype.Text `json:"category"`
}

type Mcdonald struct {
	ID           int32       `json:"id"`
	Name         string      `json:"name"`
	ImageUrl     pgtype.Text `json:"imageUrl"`
	Calories     pgtype.Text `json:"calories"`
	CaloriesUnit pgtype.Text `json:"caloriesUnit"`
	Protein      pgtype.Text `json:"protein"`
	ProteinUnit  pgtype.Text `json:"proteinUnit"`
	Carbs        pgtype.Text `json:"carbs"`
	CarbsUnit    pgtype.Text `json:"carbsUnit"`
	Fat          pgtype.Text `json:"fat"`
	FatUnit      pgtype.Text `json:"fatUnit"`
	Category     pgtype.Text `json:"category"`
}

type OnboardingResponse struct {
	ID            int64              `json:"id"`
	UserID        string             `json:"userId"`
	Goal          pgtype.Text        `json:"goal"`
	Weight        int32              `json:"weight"`
	HeightFeet    string             `json:"heightFeet"`
	HeightInches  string             `json:"heightInches"`
	AgeRange      pgtype.Text        `json:"ageRange"`
	DaysPerWeek   pgtype.Text        `json:"daysPerWeek"`
	ActivityLevel pgtype.Text        `json:"activityLevel"`
	Cravings      string             `json:"cravings"`
	Dislikes      string             `json:"dislikes"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
}

type Popeye struct {
	ID           int32       `json:"id"`
	Name         string      `json:"name"`
	ImageUrl     pgtype.Text `json:"imageUrl"`
	Calories     pgtype.Text `json:"calories"`
	CaloriesUnit pgtype.Text `json:"caloriesUnit"`
	Protein      pgtype.Text `json:"protein"`
	ProteinUnit  pgtype.Text `json:"proteinUnit"`
	Carbs        pgtype.Text `json:"carbs"`
	CarbsUnit    pgtype.Text `json:"carbsUnit"`
	Fat          pgtype.Text `json:"fat"`
	FatUnit      pgtype.Text `json:"fatUnit"`
	Category     pgtype.Text `json:"category"`
}

type Subway struct {
	ID           int32       `json:"id"`
	Name         string      `json:"name"`
	ImageUrl     pgtype.Text `json:"imageUrl"`
	Calories     pgtype.Text `json:"calories"`
	CaloriesUnit pgtype.Text `json:"caloriesUnit"`
	Protein      pgtype.Text `json:"protein"`
	ProteinUnit  pgtype.Text `json:"proteinUnit"`
	Carbs        pgtype.Text `json:"carbs"`
	CarbsUnit    pgtype.Text `json:"carbsUnit"`
	Fat          pgtype.Text `json:"fat"`
	FatUnit      pgtype.Text `json:"fatUnit"`
	Category     pgtype.Text `json:"category"`
}

type Tacobell struct {
	ID           int32       `json:"id"`
	Name         string      `json:"name"`
	ImageUrl     pgtype.Text `json:"imageUrl"`
	Calories     pgtype.Text `json:"calories"`
	CaloriesUnit pgtype.Text `json:"caloriesUnit"`
	Protein      pgtype.Text `json:"protein"`
	ProteinUnit  pgtype.Text `json:"proteinUnit"`
	Carbs        pgtype.Text `json:"carbs"`
	CarbsUnit    pgtype.Text `json:"carbsUnit"`
	Fat          pgtype.Text `json:"fat"`
	FatUnit      pgtype.Text `json:"fatUnit"`
	Category     pgtype.Text `json:"category"`
}

type Wendy struct {
	ID           int32       `json:"id"`
	Name         string      `json:"name"`
	ImageUrl     pgtype.Text `json:"imageUrl"`
	Calories     pgtype.Text `json:"calories"`
	CaloriesUnit pgtype.Text `json:"caloriesUnit"`
	Protein      pgtype.Text `json:"protein"`
	ProteinUnit  pgtype.Text `json:"proteinUnit"`
	Carbs        pgtype.Text `json:"carbs"`
	CarbsUnit    pgtype.Text `json:"carbsUnit"`
	Fat          pgtype.Text `json:"fat"`
	FatUnit      pgtype.Text `json:"fatUnit"`
	Category     pgtype.Text `json:"category"`
}
