// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"
)

const getMcdonaldsProduct = `-- name: GetMcdonaldsProduct :one
SELECT id, name, image_url, calories, calories_unit, protein, protein_unit, carbs, carbs_unit, fat, fat_unit, category FROM mcdonalds
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMcdonaldsProduct(ctx context.Context, id int32) (Mcdonald, error) {
	row := q.db.QueryRow(ctx, getMcdonaldsProduct, id)
	var i Mcdonald
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageUrl,
		&i.Calories,
		&i.CaloriesUnit,
		&i.Protein,
		&i.ProteinUnit,
		&i.Carbs,
		&i.CarbsUnit,
		&i.Fat,
		&i.FatUnit,
		&i.Category,
	)
	return i, err
}

const getMcdonaldsProducts = `-- name: GetMcdonaldsProducts :many
SELECT id, name, image_url, calories, calories_unit, protein, protein_unit, carbs, carbs_unit, fat, fat_unit, category FROM mcdonalds
`

func (q *Queries) GetMcdonaldsProducts(ctx context.Context) ([]Mcdonald, error) {
	rows, err := q.db.Query(ctx, getMcdonaldsProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mcdonald
	for rows.Next() {
		var i Mcdonald
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImageUrl,
			&i.Calories,
			&i.CaloriesUnit,
			&i.Protein,
			&i.ProteinUnit,
			&i.Carbs,
			&i.CarbsUnit,
			&i.Fat,
			&i.FatUnit,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubwayProducts = `-- name: GetSubwayProducts :many
SELECT id, name, image_url, calories, calories_unit, protein, protein_unit, carbs, carbs_unit, fat, fat_unit, category FROM subway
`

func (q *Queries) GetSubwayProducts(ctx context.Context) ([]Subway, error) {
	rows, err := q.db.Query(ctx, getSubwayProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subway
	for rows.Next() {
		var i Subway
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImageUrl,
			&i.Calories,
			&i.CaloriesUnit,
			&i.Protein,
			&i.ProteinUnit,
			&i.Carbs,
			&i.CarbsUnit,
			&i.Fat,
			&i.FatUnit,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
