CREATE TABLE mcdonalds (
    id            SERIAL PRIMARY KEY,
    name          TEXT NOT NULL,
    image_url     TEXT,
    calories      TEXT,
    calories_unit TEXT,
    protein       TEXT,
    protein_unit  TEXT,
    carbs         TEXT,
    carbs_unit    TEXT,
    fat           TEXT,
    fat_unit      TEXT,
    category      TEXT
);


CREATE TABLE subway (
    id            SERIAL PRIMARY KEY,
    name          TEXT NOT NULL,
    image_url     TEXT,
    calories      TEXT,
    calories_unit TEXT,
    protein       TEXT,
    protein_unit  TEXT,
    carbs         TEXT,
    carbs_unit    TEXT,
    fat           TEXT,
    fat_unit      TEXT,
    category      TEXT
);

create table onboarding_responses (
  id bigint generated by default as identity not null,
  user_id text not null,
  goal text null,
  weight integer not null,
  height_feet text not null,
  height_inches text not null,
  age_range text null,
  days_per_week text null,
  activity_level text null,
  cravings text not null,
  dislikes text not null,
  created_at timestamp with time zone not null default now(),
  constraint onboarding_responses_pkey primary key (id)
); 

CREATE TABLE chickfila(
    id            SERIAL PRIMARY KEY,
    name          TEXT NOT NULL,
    image_url     TEXT,
    calories      TEXT,
    calories_unit TEXT,
    protein       TEXT,
    protein_unit  TEXT,
    carbs         TEXT,
    carbs_unit    TEXT,
    fat           TEXT,
    fat_unit      TEXT,
    category      TEXT
);

CREATE TABLE burgerking(
    id            SERIAL PRIMARY KEY,
    name          TEXT NOT NULL,
    image_url     TEXT,
    calories      TEXT,
    calories_unit TEXT,
    protein       TEXT,
    protein_unit  TEXT,
    carbs         TEXT,
    carbs_unit    TEXT,
    fat           TEXT,
    fat_unit      TEXT,
    category      TEXT
);
